---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myk8sblog
  namespace: myk8sblog
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: myk8sblog
    spec:
      containers:
      - name: myk8sblog
        image: dcasati/myk8sblog:2b9e08c
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
